/**
 * Generic API response wrapper for consistent data fetching across the application.
 * @template T The type of the data returned in the response.
 */
export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Represents a registered user in the system.
 */
export interface User {
  id: string;
  email: string;
  created_at: string;
}

/**
 * Represents a product item that can be stored in warehouses.
 */
export interface Product {
  id: string;
  user_id: string;
  name: string;
  sku: string;
  category: string | null;
  price: number | string | null;
  unit?: string | null;
  description?: string | null;
  is_active?: boolean;
  created_at: string;
  updated_at?: string;
  min_quantity?: number;
}

/**
 * Represents a physical storage location or facility.
 */
export interface Warehouse {
  id: string;
  user_id: string;
  name: string;
  location: string | null;
  max_capacity: number;
  type?: string | null;
  created_at: string;
}

export interface WarehouseWithUtilization extends Warehouse {
  total_stock: number;
  utilization_percent: number;
}

export type UtilizationStatus = "safe" | "warning" | "danger" | "critical";

export function getUtilizationStatus(
  percent: number
): UtilizationStatus {
  if (percent <= 60) return "safe";
  if (percent <= 80) return "warning";
  if (percent <= 90) return "danger";
  return "critical";
}

/**
 * Represents the inventory level of a specific product in a specific warehouse.
 */
export interface Stock {
  id: string;
  product_id: string;
  warehouse_id: string;
  quantity: number;
  updated_at: string;
}

/**
 * Extended Stock type that includes full Product and Warehouse details.
 * Used for UI views where joined data is necessary.
 */
export interface StockWithDetails extends Stock {
  product: Product;
  warehouse: Warehouse;
}

/**
 * Represents a specific actionable point or observation within an AI insight.
 */
export interface InsightItem {
  title: string;
  description: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  action: string | null;
}

/**
 * Represents a complete analysis generated by the AI model regarding inventory health.
 */
export interface AiInsight {
  summary: string;
  items: InsightItem[];
  generated_at: string;
  model: string;
}

export type InsightPriority = "critical" | "high" | "medium" | "low";

export interface RestockItem {
  product_name: string;
  sku: string;
  warehouse_name: string;
  current_quantity: number;
  unit: string;
  priority: InsightPriority;
  suggested_reorder_qty: number;
  reason: string;
}

export interface RestockInsight {
  recommendations: RestockItem[];
  summary: string;
  generated_at: string;
}

export interface InsightMeta {
  model: string;
  context_tokens: number;
  input_tokens: number | null;
  output_tokens: number | null;
}

export interface InsightResponse<T> {
  success: boolean;
  data: T;
  meta: InsightMeta;
  error?: string;
}

/**
 * Represents a single message exchange in the AI assistant chat interface.
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  created_at: string;
}

export interface ChatRequest {
  message: string;
  history: ChatMessage[];
}
